spring:
  datasource:
    url: jdbc:mysql://ssts-database.cvrfezvt4mni.ap-northeast-2.rds.amazonaws.com:3306/sstsDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: admin22
    password: ssts1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect  # ★★★
    defer-datasource-initialization: true # ★★★

  sql:
    init:
      mode: always
      data-locations: classpath:data-init.sql
      #schema-locations: classpath:schema-init.sql
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true